### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by ZM71**

### CODE REVIEW

**Comment by ZM71** [comment]
Please ignore this i created the request wrong way.

**Comment by Pyenb** [comment]
Disregarding that, I don't really understand what this is trying to achieve?

**Comment by ZM71** [comment]
Is it possible to merge 2 vms?

**Comment by Pyenb** [comment]
What do you mean? A VM is like it's own Computer, so can you merge 2 PC's? It depends on what you really want.

**Comment by ZM71** [comment]
The storage doesn't come from nowhere it uses the real disk to get that space that the user desires, that's atleast how VMware works.

**Pull request closed without merging**
